steps:
  # Step 1: Install dependencies inside /src
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci', '--prefix', 'src']
    id: 'Install Dependencies'

  # Step 2: Run the build script, also inside /src
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build', '--prefix', 'src']
    id: 'Build Application'
    waitFor: ['Install Dependencies']

  # Step 3: Run tests, also inside /src
  - name: 'gcr.io/cloud-builders/npm'
    args: ['test', '--prefix', 'src']
    id: 'Run Tests'
    waitFor: ['Build Application']
    entrypoint: 'bash'
    args: ['-c', 'npm test --prefix src || exit 0']

# The build script creates 'dist' inside 'src', so we grab it from there
artifacts:
  objects:
    location: 'gs://welltegra-prod-bucket1/'
    paths:
      - 'src/dist/**'

options:
  logging: CLOUD_LOGGING_ONLY
