steps:
  # Step 1: Install dependencies inside /src
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci', '--prefix', 'src']
    id: 'Install Dependencies'

  # Step 2: Run the CSS build script, also inside /src
  # This is the correct build command from your project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build:css', '--prefix', 'src']
    id: 'Build CSS'
    waitFor: ['Install Dependencies']

  # Step 3: Manually copy all files into a 'dist' folder
  # This creates the final website folder to be deployed
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating dist directory inside src..."
        mkdir -p src/dist
        
        echo "Copying all project files to src/dist..."
        # We rsync everything from /src into /src/dist
        # We must exclude node_modules and the dist folder itself
        rsync -av --exclude='node_modules' --exclude='dist' src/ src/dist/
    id: 'Copy Files to Dist'
    waitFor: ['Build CSS']

# The artifacts are now in 'src/dist/'
artifacts:
  objects:
    location: 'gs://welltegra-prod-bucket1/'
    paths:
      - 'src/dist/**'

options:
  logging: CLOUD_LOGGING_ONLY
